### PR TITLE
iconsets update

### PR DESCRIPTION
**Pull request by Neustradamus**
- iconsets/system/README
- psi/psiLogo -> psi/logo

### CODE REVIEW

**Comment by tehnick** [comment]
@Ri0n Why have you merged this PR?

Where are no such files in sources tree:
* psi/logo
* psi/main
* psi/logo

Will it work at all?

Unfortunately @Neustradamus uses GitHub UI for preparing his PRs and do not check the result of proposed changes. And this is sad.

**Comment by Ri0n** [comment]
It's not a filename. It's an icon name and the mapping is defined in icondef.xml

**Comment by tehnick** [comment]
Ok, this was too quick conclusion.

But why should they differ? It would be better to bring them to the same names, do not it?

**Comment by Ri0n** [comment]
sometimes. in the names we use prefixes similar to directories. but all the files are in the same directory.

**Comment by tehnick** [comment]
I am about:
* iconsets/system/default/psilogo.png
* iconsets/system/default/psimain.png

**Comment by tehnick** [comment]
Because other files are with the same names:
* iconsets/system/default/logo_16.png
* iconsets/system/default/logo_32.png
* iconsets/system/default/logo_48.png
* iconsets/system/default/logo_64.png
* iconsets/system/default/logo_128.png

**Pull request merged**
