### PR TITLE
Remove README.html

### PR DESCRIPTION
**Pull request by jubalh**
We have the markdown file already. Don't need to maintain two files.
GitHub preview of markdown is good enough.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@jubalh: The README.html is needed:
- https://github.com/psi-im/psi/commit/21521a11b3d3e7b5e9db1fcb9fe1744a94b9bc23

**Comment by jubalh** [comment]
For what?

**Comment by Neustradamus** [comment]
@jubalh: https://github.com/psi-im/psi/search?q=README.html
@tehnick has done a revert for this.

**Comment by tehnick** [comment]
https://github.com/psi-im/psi/commit/e9613d51bbf49bdb2c4d19e0cd8b6f8a00434e13#commitcomment-67987223

**Comment by tehnick** [comment]
We cannot use Markdown in UI directly until we stop support of Qt < 5.14.

**Pull request merged**
