### PR TITLE
Psi MUC Room in About tab of About window

### PR DESCRIPTION
**Pull request by Neustradamus**
Psi MUC Room in About tab of About window and solves #402.

### CODE REVIEW

**Review by Ri0n — CHANGES_REQUESTED** [review]
please follow common rules of naming ui lables. e.g. ul_psiWww. ul_psiMuc.

I just checked and it doesn't look nice. The words Website / Muc Room have to be moved out of links

**Comment by Neustradamus** [comment]
@Ri0n: I have requested you a little help to move the "Website:" and "MUC Room:".

**Comment by Neustradamus** [comment]
Currently, the psi-im.org link is "uRLLabel1", it is for this that I have added "uRLLabel2" ;)

I will update this part.

**Comment by Neustradamus** [comment]
@Ri0n: Label updated with the good prefix...

**Comment by Ri0n** [comment]
you can use grid and form layout to have two columns (the first for labels, and the second for llinks)

**Pull request closed without merging**
