### PR TITLE
A better description for MacOS

### PR DESCRIPTION
**Pull request by Neustradamus4**

### CODE REVIEW

**Comment by Ri0n** [comment]
please add some PR description describing the reason and the result

**Comment by tehnick** [comment]
@Ri0n 
mac/macos_definitions.cmake:set(MACOSX_BUNDLE_LONG_VERSION_STRING ${CLIENT_NAME} ${APP_VERSION})

@Neustradamus 
Reject.

**Comment by Neustradamus4** [comment]
It is "Version" string for old MacOS system, my request is good:
- https://www.google.com/search?tbm=isch&q=CFBundleGetInfoString

**Comment by tehnick** [comment]
> It is "Version" string for old MacOS systems

We do not support macOS older than 10.13 and all is fine with "Version" string there:
https://susepaste.org/view/raw/82214099

**Comment by Neustradamus4** [comment]
Like your screenshot, you confirm that the option has been removed from your MacOS system.

But I confirm, it was a string with software version, not a description:
- https://stackoverflow.com/questions/1295354/changing-the-version-in-the-info-plist-file-so-that-correct-version-will-show-up
- http://forums.livecode.com/viewtopic.php?t=15295

We can remove the key and string lines directly too, it is a good solution instead of solve it.

**Pull request closed without merging**
