### PR TITLE
setWindowFlags updates

### PR DESCRIPTION
**Pull request by Neustradamus**
- Replace `Qt::WindowMinimizeButtonHint | Qt::WindowMaximizeButtonHint`
-> `Qt::WindowMinMaxButtonsHint`

### CODE REVIEW

**Comment by Neustradamus** [comment]
Any news?
I have seen removal of Tip Of The Day part ^^

**Comment by Ri0n** [comment]
a lot of unrelated changes which break clang-format formatting.
I won't merge it till it's fixed.

**Comment by Vitozz** [comment]
On my opinion this is useless changes. Disabling help buttons using flags it is a bad solution. Better to change whatsThis methods to tooltips or something like this.

**Comment by Neustradamus** [comment]
@ri0n, @Vitozz: My original PR has been modified because @tehnick has already removed "Qt::WindowContextHelpButtonHint" and I have recently added the good part about "Qt::AA_DisableWindowContextHelpButton" which now work for Qt 5.10.1+.

It is only: Qt::WindowMinimizeButtonHint | Qt::WindowMaximizeButtonHint
-> Qt::WindowMinMaxButtonsHint

**Comment by Ri0n** [comment]
no requested changes for a long time

**Comment by Neustradamus** [comment]
It is done by @Ri0n after closing this PR (done by me in January 2019):
- https://github.com/psi-im/psi/commit/e069c1e61ebefa2916d2513ce2fbef1187453e39

**Pull request closed without merging**
