### PR TITLE
vcard/VCard/User Info -> vCard + Adding for MUC Room

### PR DESCRIPTION
**Pull request by Neustradamus**
vcard/VCard/User Info -> vCard + Adding for MUC Room and solves #541.

### CODE REVIEW

**Comment by Ri0n** [comment]
I don't like magic indexes..

**Comment by Ri0n** [comment]
I thought about it a little bit.
vCard is a file format, not some common term for a visit card.
Therefore a term "User info" should be more understandable for xmpp newbies.
So I'd prefer to keep "user info" in visible for users texts while using vcard for code identifiers.

And please stop doing meaningless changes in comments and empty lines, stop moving stuff w/o a good reason.

**Comment by Neustradamus** [comment]
There are already vCard, it is to harmonize.

I have update your "MUC Room information" to be better, and there are informations.

Currently, there is a mix with "vCard" and "Information", it is not same: "chat_info" vs "gchat_info".

With my PR:
In function, it is VCard
In the text, it is vCard instead of VCard, the good name is vCard: https://en.wikipedia.org/wiki/VCard
chat_vcard (vCard in chat) and gchat_vcard (vCard in groupchat) and gchat_infos (yours feature)

**Comment by Neustradamus** [comment]
@Ri0n: I have forgotten to inform you, my PR solves a bad "gchat_templates" to "chat_templates" too.

**Comment by Neustradamus** [comment]
@mashiro-tan: Have you tested the PR, badly @Ri0n has closed it.

There are:
Replace the "Information" button to "Informations" (because there are informations) and because there was a "conflict" in function names with vCard ("chat_info" and "gchat_info")
- vCard harmonization
- Adding for groupchat like chat

**Comment by Neustradamus** [comment]
This PR has been replaced by:
- https://github.com/psi-im/psi/pull/660
- https://github.com/psi-im/psi/pull/661
- https://github.com/psi-im/psi/pull/662
- https://github.com/psi-im/psi/pull/663
- https://github.com/psi-im/psi/pull/664

**Pull request closed without merging**
