### PR TITLE
Set Exec key to handle a single URL

### PR DESCRIPTION
**Pull request by GreenLunar**

### CODE REVIEW

**Comment by GreenLunar** [comment]
See http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

Code | Description
------------ | -------------
%u | A single URL. Local files may either be passed as file: URLs or as file path.
%U | A list of URLs. Each URL is passed as a separate argument to the executable program. Local files may either be passed as file: URLs or as file path.

**Comment by Ri0n** [comment]
Just wondering what if we do opposite thing instead like open multiple urls

**Comment by GreenLunar** [comment]
I do not know if it is possible to make a hyperlink with more than a JID.  One certainly put several JIDs in a command-line line.

**Comment by Neustradamus** [comment]
@GreenLunar: What is the status of this PR?

**Comment by GreenLunar** [comment]
Hi @Neustradamus!
It's great to read from you.

> What is the status of this PR?

I don't know.
May you do it instead?

**Comment by GreenLunar** [comment]
> Just wondering what if we do opposite thing instead like open multiple urls

@Ri0n do you've a use case to that?

The issue as I see the state of affairs 
are as follows:
1) Psi doesn't handle multiple URLs
* The argument `%U` might pose a threat to security by spamming PSI with plenty of URL and attempting to cause to a memory leakage (maybe) or threshhold the CPU (or whatever) - I can't think of anything other than that.

**Comment by Ri0n** [comment]
ah conflicts..

Well wrt usecase. not in my case. But I guess some may find it useful for automation

**Pull request closed without merging**
