### PR TITLE
Add "Simple Smileys" v. 1.7 by Leo Bolin iconset for Psi-IM

### PR DESCRIPTION
**Pull request by lyn1337**
Greetings!
I've found some totally free emoticons on the www (see the link below) and wrapped them into an iconset for Psi – can't harm! All of them were tested.

As an act of upholding the etiquette, I added credits though.

In case this PR is fine, I'd add more of what I have packaged.

~Regards

http://simplesmileys.org/

### CODE REVIEW

**Comment by Ri0n** [comment]
Look nice!  :-)
What do you think about emoji support?

**Comment by lyn1337** [comment]
@Ri0n 
Agree! Found these look quite clear, especially on lighter backgrounds and themes.
I can offer you any support you need for it. Also, I suggest to package this iconset with instructions and sending it to the author.

**Comment by Ri0n** [comment]
I mean those Unicode smileys like here http://getemoji.com/
It would be nice to use them by default for text representation.
Otherwise I'd prefer to have this smiley pack as *.jisp file

**Comment by lyn1337** [comment]
@Ri0n 
I agree; packaged this as .jisp now.

To my taste, I'd prefer to have no default set at all, since it is quite difficult to fit one emoticon theme.
Speaking of those emoticons from the Unicode block, they aren't quite "readable", are they?
It would make no sense to implement them via rasterization, but I once had the idea to maybe bring down some chatwindow menu which holds the Unicode range U+1F600 … U+1F64F to be inserted.
Maybe introducing some checkbox in the settings for enabling that, no?

**Comment by Ri0n** [comment]
Well probably I explained it bad. what I mean is having "`😊`" instead of ":-)" as a first variant in your icondef.xml.
This usually perfectly matches with all modern messengers. It doesn't matter what's on a picture. It's about how clients interpret it. And even clients without smileys pack will anyway show good text representation as you see above. 

About your jisp file. I'll put it here https://github.com/psi-plus/resources/tree/master/iconsets/emoticons a little later if you don't mind.

**Comment by lyn1337** [comment]
@Ri0n 
Ah, I see now. I experienced those to not work at all on Psi <--> Pidgin (-like) && unix <--> Win communication for reasons unknown. Could be added easily though at a later point.

Ofc, go ahead to put it there. Any reasons left to not merge this PR?

btw: haven't thought about that psi dev branch. just checked its webpage. you guys speak rus only, right? (seen a screenshot of the dev talk)
is psi-im.org abandoned of some sort or do they still keep a muc room up?

**Comment by Ri0n** [comment]
psi-im.org is not abandoned and muc is still alive but probably it's not accessible for everyone right now.
We speak English and Russian.. well most of us.

About merging..
Psi had just default smiley pack for years and it has just one icon pack for anything. I'd prefer to keep this traditions and put all extra iconpacks to some other place.
Or It's possible to replace current default pack but in this case I think it's really good idea to introduce Unicode smileys with that.

**Comment by lyn1337** [comment]
@Ri0n 
I see… the old builds just kept me thinking.

So Psi is treated like some classic version? I'll look into those Unicodies now then. Thanks!

**Comment by Ri0n** [comment]
I promise new builds will be available this year :-)
I can't say how soon. I thought to release a new version last month but it turned out I have a lot of stuff to do with my other projects, personal life and work.

**Comment by lyn1337** [comment]
@Ri0n 
I bet it is indeed lots of work, but wouldn't automated nightlys be a good thing to start with? Maybe some public muc, too? :wink:
Gotta look into the code some more, I'd like to start working on the German translation a little more and do a PR there.

**Comment by Ri0n** [comment]
Ah yes about muc. You can always visit psi-dev@conference.jabber.ru
And we have some builds there. It's fine to speak English there.

**Comment by Ri0n** [comment]
Thanks for your great work! I can accept this pull request, but you smiley pack will live here https://github.com/psi-plus/resources/blob/master/iconsets/emoticons/simple.jisp
Ping me if you have any updates.

What I could accept as defaults replacement
1) Bigger sized smileys. I think 22px would be nice on regular FullHD monitor. But multiple packs with different resolutions is fine as well.
2) Number of smileys is approximately the same as in current default smileys pack or maybe even less.
3) All smileys has Emoji as default text and have popular alternative texts.

Regards

**Comment by lyn1337** [comment]
Thanks for adding and your compliments.

I will be working on this, as soon as higher resolutions are possible / finished.

~lyn

**Comment by Neustradamus** [comment]
@lyn1337 Any news?

**Pull request closed without merging**
